name: Install Apache and deploy site
  hosts: all
  become: yes
  tasks:
     name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    name: Copy index.html
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
